DrpLogin="//a[text()='Login']"
InpUserName="//input[@name='username']"
InpPwd="//input[@name='password']"
BtnLogin="//button[@type='submit']"
MsgInvalidLogin="//p[text()='Invalid credentials']"
MainMenu="//ul[@class='oxd-main-menu']"
MainPageHeader="//span[@class='oxd-topbar-header-breadcrumb']"
MsgBlankUsername="(//span[text()='Required'])[1]"
MsgBlankPwd="(//span[text()='Required'])[2]"
DrpUser="//li[@class='oxd-userdropdown']"
DrpLogOut="//a[text()='Logout']"
LoginSlot="//div[@class='orangehrm-login-slot']"
LoginHeader="//h5[text()='Login']"